ENVIRONMENTS :=						\
	NCCL_NET_PLUGIN=tcpx			\
	NCCL_IB_DISABLE=1				\
	NCCL_DEBUG=INFO					\
	NCCL_SOCKET_IFNAME=$(IFNAME)	\
	NCCL_TCPX_IFNAMES=$(IFNAME)		\
	$(ADDITIONAL_ENV)

ARGUMENTS := $(SERVER) $(ADDRESS)
