LD_LIBRARY_PATH=$(RCCL_ROOT)/lib

ENVIRONMENTS = 											\
	NCCL_NET_PLUGIN=rccl-tcpx							\
	NCCL_IB_DISABLE=1									\
	NCCL_DEBUG=INFO										\
	NCCL_SOCKET_IFNAME=$(IFNAME)						\
	NCCL_TCPX_IFNAMES=$(IFNAME)							\

ARGUMENTS := $(SERVER) $(ADDRESS)
