IFNAME := enp4s0
DEBUG_LEVEL := INFO
PLUGIN_NAME := tcpx

ENVIRONMENTS :=						\
	NCCL_SOCKET_IFNAME=$(IFNAME)	\
	NCCL_IB_DISABLE=1				\
	NCCL_DEBUG=$(DEBUG_LEVEL)		\
	NCCL_NET_PLUGIN=$(PLUGIN_NAME)	\
	NCCL_TCPX_IFNAMES=$(IFNAME)		\
	LD_LIBRARY_PATH=$(shell pwd)

ARGUMENTS := 0 192.168.0.182
